### ISSUE TITLE
Null value & False value support

### ISSUE THREAD

**Issue by orocesar** [gextech/binding-util#3] opened 2014-12-04 01:04 UTC
When the property source object's value is null or false, it must be setted

**Comment by anallely** [comment] 2015-01-29 15:02
Solved

**Comment by anallely** [comment] 2015-03-18 18:48
The issue was re-opened because it is failing when dest object has already values, they are now overriden with null/false values of source objects

@hgmiguel  pull requested a test that must pass when the issue is solved

**Comment by anallely** [comment] 2015-03-19 23:33
It was fixed on version #24 (0.1.16)

**Closed by anallely** 2015-03-19 23:33 UTC
Labels: bug
